name: Combine Emojis and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight (UTC)

jobs:
  combine_emojis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow unidecode

      - name: Clone FluentUI Emoji repository
        run: |
          git clone https://github.com/microsoft/fluentui-emoji.git

      - name: Clone Animated Fluent Emojis repository
        run: |
          git clone https://github.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis.git

      - name: Run Python script to combine emojis
        run: |
          python src/update_emojis/main.py
        env:
          dir_regular: fluentui-emoji/assets
          dir_animated: Animated-Fluent-Emojis/Emojis
          dir_output: ./Emojis

      - name: Remove cloned repositories
        run: |
          rm -rf fluentui-emoji
          rm -rf Animated-Fluent-Emojis

      - name: Check for changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "Combined emojis with latest data"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: combined-emojis-update
          commit-message: Combined emojis with latest data
          title: "Combined emojis update"
          body: "This pull request was created automatically by the GitHub Actions workflow."
          labels: update, auto-generated
          reviewers: malte9799
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
