name: Gource Action
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        
      - name: 'Gource Action'
        uses: NBprojekt/gource-action@v1.2.1

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v4
        with:
          name: Gource
          path: ./gource/gource.mp4