name: Generate Gource Visualization

on:
  push:
    branches:
      - main  # or the branch you want to run this on
  workflow_dispatch:  # Allows manual trigger

jobs:
  gource-visualization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Gource and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gource ffmpeg xvfb

      - name: Start Xvfb
        run: |
          Xvfb :0 -screen 0 1920x1080x24 &
          export DISPLAY=:0

      - name: Make script executable
        run: chmod +x ./src/gource-visualization/gource.sh

      - name: Run Gource Visualization
        run: |
          ./src/gource-visualization/gource.sh '${{ github.event.repository.name }}' ./output-visualization

      - name: Upload Visualization
        uses: actions/upload-artifact@v4
        with:
          name: gource-visualization
          path: ./output-visualization.mp4
