name: Update Emojis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update_emojis:
    runs-on: ubuntu-latest

    steps:
      - name: Clone microsoft/fluentui-emoji
        uses: actions/checkout@v4
        with:
          repository: microsoft/fluentui-emoji
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: emojis/regular

      - name: Clone Tarikul-Islam-Anik/Animated-Fluent-Emojis
        uses: actions/checkout@v4
        with:
          repository: Tarikul-Islam-Anik/Animated-Fluent-Emojis
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: emojis/animated

      - uses: actions/checkout@v4
        with:
          path: cdn

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: |
          pip install unidecode
          pip install Pillow

      - name: Execute script
        run: python cdn/scripts/update_emojis.py
        
      - name: Downscale PNG images
        run: |
          cd cdn
          for emoji in $(ls Emojis); do
            for style in 3d animated; do
              if [ -d "Emojis/$emoji/$style" ]; then
                for size in 128 64; do
                  if [ -d "Emojis/$emoji/$style/default" ]; then
                    for skinTone in $(ls Emojis/$emoji/$style); do
                      convert -coalesce Emojis/$emoji/$style/$skinTone/256.png -resize $sizex$size Emojis/$emoji/$style/$skinTone/$size.png
                    done
                  else
                    convert -coalesce Emojis/$emoji/$style/256.png -resize $sizex$size Emojis/$emoji/$style/$size.png
                  fi
                done
              fi
            done
          done

      - name: Add changes
        run: |
          cd cdn
          git config http.postBuffer 524288000
          git lfs track "animated/*.png"
          git add Emojis -f

      - name: Push changes
        run: |
          cd cdn
          git diff --cached --binary | wc -c
          git config user.name github-actions[bot]
          git config user.email github-actions@github.com
          if ! git diff-index --quiet HEAD; then
            git commit -m "Updates"
            git push -v
          else
            echo "No changes detected!"
          fi
